# Generated by Django 3.0.5 on 2020-05-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='districtkey',
            name='id',
        ),
        migrations.AddField(
            model_name='districtkey',
            name='district_find',
            field=models.CharField(default='no div', max_length=30, primary_key=True, serialize=False),
        ),
    ]
