# Generated by Django 3.0.5 on 2020-05-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_auto_20200502_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='districtkey',
            name='district_find',
        ),
        migrations.AddField(
            model_name='districtkey',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
