# Generated by Django 3.0.5 on 2020-05-02 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0003_auto_20200502_1612'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DistrictKey',
        ),
    ]
