# Generated by Django 3.0.5 on 2020-05-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0005_bhopaldata_chambaldata_gwaliordata_indoredata_jabalpurdata_narmadapuramdata_rewadata_sagardata_shahd'),
    ]

    operations = [
        migrations.CreateModel(
            name='divisionDistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('div_no', models.IntegerField()),
                ('district_name', models.CharField(max_length=40)),
            ],
        ),
    ]
