# Generated by Django 3.0.5 on 2020-05-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0006_divisiondistrict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bhopaldata',
            name='aadhaar_no',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='chambaldata',
            name='aadhaar_no',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='gwaliordata',
            name='aadhaar_no',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='indoredata',
            name='aadhaar_no',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='jabalpurdata',
            name='aadhaar_no',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='narmadapuramdata',
            name='aadhaar_no',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='rewadata',
            name='aadhaar_no',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='sagardata',
            name='aadhaar_no',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='shahdoldata',
            name='aadhaar_no',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='ujjaindata',
            name='aadhaar_no',
            field=models.BigIntegerField(),
        ),
    ]
